#ifndef CORDIAL_BTSTACK_CONFIG_H
#define CORDIAL_BTSTACK_CONFIG_H

#define ENABLE_BTSTACK_ASSERT
#define ENABLE_SOFTWARE_AES128
#define ENABLE_MICRO_ECC_FOR_LE_SECURE_CONNECTIONS
#define ENABLE_LE_CENTRAL
#define ENABLE_LE_SECURE_CONNECTIONS
#define ENABLE_LE_PRIVACY_ADDRESS_RESOLUTION
/* Failed re-encryption must not implicitly delete a saved native bond. */
#define ENABLE_LE_PROACTIVE_AUTHENTICATION
#ifdef ENABLE_GATT_CLIENT_CACHING
#error "Native GATT cache writes are outside this adapter's pairing storage contract"
#endif
#define ENABLE_EXPLICIT_PAIRING_ON_SECURITY_REQUEST
#define ENABLE_LE_DATA_LENGTH_EXTENSION
#define ENABLE_GATT_CLIENT_PAIRING
#define HCI_ACL_CHUNK_SIZE_ALIGNMENT 4
/* The Pico transport has a 1024-byte packet including its indicator/header. */
#define HCI_ACL_PAYLOAD_SIZE 1016
#define HCI_OUTGOING_PRE_BUFFER_SIZE 4
#define HCI_RESET_RESEND_TIMEOUT_MS 100
#define MAX_NR_HCI_CONNECTIONS 4
#define MAX_NR_HID_HOST_CONNECTIONS 4
#define MAX_NR_GATT_CLIENTS 4
#define MAX_NR_L2CAP_CHANNELS 12
#define MAX_NR_L2CAP_SERVICES 3
#define MAX_NR_SM_LOOKUP_ENTRIES 4
#define MAX_NR_WHITELIST_ENTRIES 8
#define MAX_NR_LE_DEVICE_DB_ENTRIES 8
#define NVM_NUM_DEVICE_DB_ENTRIES 8
#define NVM_NUM_LINK_KEYS 8
#define MAX_ATT_DB_SIZE 128

#endif
