[package]
name = "cordial-memory-arm"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
cordial-btstack = { path = "../../adapters/btstack", features = ["ffi", "classic"] }
cordial-core = { path = "../../crates/cordial-core" }
cordial-protocol = { path = "../../crates/cordial-protocol" }
embassy-futures = "=0.1.2"
talc = { version = "=5.1.1", features = ["counters"] }
cortex-m-rt = "=0.7.7"
serde_json = { version = "=1.0.151", default-features = false, features = ["alloc"] }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
