// Exercises the built desktop renderer with simulated state and controlled replies.
// Run from desktop: xvfb-run -a node test/device-ui.mjs
import { _electron } from "playwright";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import assert from "node:assert/strict";

const profile = await mkdtemp(join(tmpdir(), "cordial-device-ui-"));
await writeFile(join(profile, "preferences.json"), JSON.stringify({ notifyLowBattery: false, notifyConnections: false }));
const env = { ...process.env, CORDIAL_DESKTOP_SIMULATE: "1" };
delete env.ELECTRON_RUN_AS_NODE;
const app = await _electron.launch({ args: ["--no-sandbox", ".", `--user-data-dir=${profile}`], env });
const page = await app.firstWindow();
const errors = [];
page.on("pageerror", (error) => errors.push(String(error)));
try {
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setContentSize(1100, 900));
  await page.getByRole("button", { name: /Example Keys/ }).first().click();
  await page.getByRole("group", { name: "Backlight", exact: true }).waitFor();
  const state = await page.evaluate(() => window.cordial.state());
  const entry = state.devices.find((d) => d.name === "Example Keys Wireless");
  assert.ok(entry?.settings?.current);
  const cachedSettings = entry.settings;
  const enabled = entry.settings.settings.find((s) => s.key === "backlight.enabled");
  Object.assign(enabled, { managed: false, desired: null, observed: null, state: "unmanaged" });
  await app.evaluate(({ ipcMain }, state) => {
    globalThis.uiState = state;
    globalThis.uiActions = [];
    ipcMain.removeHandler("state");
    ipcMain.handle("state", () => globalThis.uiState);
    ipcMain.removeHandler("act");
    ipcMain.handle("act", (_event, action) => {
      globalThis.uiActions.push(action);
      if (globalThis.uiHold === action.type)
        return new Promise((resolve) => { globalThis.uiReply = resolve; });
      if (globalThis.uiFail === action.type) return { ok: false, message: "Couldn't save this value." };
      return { ok: true };
    });
  }, state);
  const publish = async () => app.evaluate(({ BrowserWindow }, state) => {
    globalThis.uiState = state;
    BrowserWindow.getAllWindows()[0].webContents.send("state", state);
  }, state);
  const actions = () => app.evaluate(() => globalThis.uiActions);
  await publish();

  entry.settings.result = { kind: "apply", error: "Apply failed.", counts: null };
  await publish();
  await page.getByRole("button", { name: "Refresh", exact: true }).waitFor();
  entry.settings.result = { kind: "refresh", error: "Some settings couldn't be read.", counts: {
    device_id: entry.device.device_id, revision: 1, count: 4, read: 3, applied: 0, unchanged: 0, unsupported: 0, failed: 1, uncertain: 0,
  } };
  await publish();
  await page.getByRole("button", { name: "Retry", exact: true }).waitFor();
  entry.settings.result = { ...entry.settings.result, error: null };
  await publish();
  await page.getByRole("button", { name: "Refresh", exact: true }).waitFor();
  await app.evaluate(() => { globalThis.uiFail = "settings.refresh"; });
  await page.getByRole("button", { name: "Refresh", exact: true }).click();
  await page.getByRole("button", { name: "Retry", exact: true }).waitFor();
  assert.ok((await actions()).some((a) => a.type === "settings.refresh" && a.key === entry.key));
  await page.locator(".toast").click();
  entry.settings.result = { kind: "apply", error: "Apply failed.", counts: null };
  await publish();
  await page.getByRole("button", { name: "Retry", exact: true }).waitFor();
  await page.getByRole("tab", { name: "Details" }).click();
  await page.getByRole("tab", { name: "Settings" }).click();
  await page.getByRole("button", { name: "Retry", exact: true }).waitFor();
  await app.evaluate(() => { globalThis.uiFail = null; });
  await page.getByRole("button", { name: "Retry", exact: true }).click();
  await page.getByRole("button", { name: "Refresh", exact: true }).waitFor();
  entry.settings.result = null;
  await publish();

  const backlight = page.getByRole("group", { name: "Backlight", exact: true });
  assert.equal(await backlight.locator('[aria-pressed="true"]').count(), 0);
  await backlight.getByRole("button", { name: "Off", exact: true }).click();
  assert.equal((await actions()).filter((a) => a.type === "setting.set").length, 0);
  assert.equal(await page.getByRole("spinbutton", { name: "Timeout With Hands Away" }).inputValue(), "30");
  await page.getByRole("tab", { name: "Details" }).click();
  await page.getByRole("tab", { name: "Settings" }).click();
  await page.getByRole("button", { name: /Example Mouse/ }).first().click();
  await page.getByRole("button", { name: /Example Keys/ }).first().click();
  assert.equal(await backlight.getByRole("button", { name: "Off", exact: true }).getAttribute("aria-pressed"), "true");

  await app.evaluate(() => { globalThis.uiFail = "setting.set"; });
  await page.getByRole("button", { name: "Save", exact: true }).click();
  await page.getByText("Couldn't save this value.", { exact: true }).waitFor();
  assert.equal(await page.locator(".toast").count(), 0);
  assert.equal(await page.getByRole("button", { name: "Save", exact: true }).count(), 1);

  assert.equal((await actions()).find((a) => a.type === "setting.set").value, false);
  await app.evaluate(() => { globalThis.uiFail = null; globalThis.uiHold = "setting.set"; });
  await page.getByRole("button", { name: "Save", exact: true }).click();
  entry.pending = [{ id: 99, command: "hidpp.setting.set" }];
  await publish();
  await backlight.getByRole("button", { name: "On", exact: true }).click();
  assert.equal(await page.getByRole("button", { name: "Refresh", exact: true }).isDisabled(), true);
  assert.equal(await page.getByRole("button", { name: "Forget saved Timeout With Hands Away" }).isDisabled(), true);
  await app.evaluate(() => { globalThis.uiReply({ ok: true }); globalThis.uiHold = null; });
  Object.assign(enabled, { managed: true, desired: false, observed: false, state: "applied" });
  entry.pending = [];
  await publish();
  assert.equal(await backlight.getByRole("button", { name: "On", exact: true }).getAttribute("aria-pressed"), "true");
  assert.equal(await page.getByRole("button", { name: "Save", exact: true }).count(), 1);

  await app.evaluate(() => { globalThis.uiHold = "setting.set"; });
  await page.getByRole("button", { name: "Save", exact: true }).click();
  entry.pending = [{ id: 101, command: "hidpp.setting.set" }];
  await publish();
  await backlight.getByRole("button", { name: "Off", exact: true }).click();
  await app.evaluate(() => { globalThis.uiReply({ ok: true }); globalThis.uiHold = null; });
  Object.assign(enabled, { desired: true, observed: true });
  entry.pending = [];
  await publish();
  assert.equal(await backlight.getByRole("button", { name: "Off", exact: true }).getAttribute("aria-pressed"), "true");
  assert.equal(await page.getByRole("button", { name: "Save", exact: true }).count(), 1);
  Object.assign(enabled, { managed: false, desired: null, observed: false, state: "unmanaged" });
  await publish();
  await backlight.getByRole("button", { name: "On", exact: true }).click();
  await backlight.getByRole("button", { name: "Off", exact: true }).click();
  await page.getByRole("button", { name: "Save", exact: true }).click();
  await page.getByText("Saved", { exact: true }).waitFor();
  await backlight.getByRole("button", { name: "Off", exact: true }).click();
  assert.equal(await page.getByRole("button", { name: "Save", exact: true }).count(), 1);
  entry.device.hidpp_enabled = false;
  entry.device.normalization_state = "off";
  await publish();
  assert.equal(await page.getByRole("button", { name: "Save", exact: true }).isDisabled(), false);
  assert.equal(await page.getByRole("button", { name: "Refresh", exact: true }).isDisabled(), false);
  assert.equal(await page.getByRole("button", { name: "Apply Saved Settings", exact: true }).count(), 0);
  Object.assign(enabled, { managed: true, desired: true, observed: true, state: "applied" });

  entry.device.state = "disconnected";
  entry.device.normalization_state = "pending";
  entry.settings.current = false;
  await publish();
  assert.equal(await page.getByRole("tab", { name: "Settings" }).isDisabled(), false);
  assert.equal(await page.getByRole("button", { name: "Forget saved Backlight", exact: true }).isDisabled(), false);
  assert.equal(await page.getByRole("button", { name: "Save", exact: true }).isDisabled(), true);
  entry.device.state = "connecting";
  entry.pending = [{ id: 100, command: "device.connect" }];
  await publish();
  await page.getByRole("button", { name: "Cancel", exact: true }).click();
  assert.ok((await actions()).some((a) => a.type === "device.connect.cancel" && a.key === entry.key));

  await page.clock.install({ time: new Date("2030-01-01T00:00:00Z") });
  await page.clock.pauseAt(new Date("2030-01-01T00:00:01Z"));
  entry.pending = [];
  entry.device.state = "connected";
  entry.device.settings_state = "pending";
  entry.settings = { settings: [], current: false, state: "pending", error: null, loadError: "The adapter hasn't read these settings yet.", result: null };
  await publish();
  await page.getByText("Reading the device's settings…", { exact: true }).waitFor();
  assert.equal(await page.getByText("Couldn't read the device's settings.", { exact: true }).count(), 0);
  await page.clock.runFor(9999);
  assert.equal(await page.getByRole("button", { name: "Retry", exact: true }).count(), 0);
  await page.clock.runFor(1);
  await page.getByRole("button", { name: "Retry", exact: true }).click();
  assert.ok((await actions()).some((a) => a.type === "settings.reload"));
  assert.equal(await page.locator(".toast").count(), 0);
  await page.getByText("Reading the device's settings…", { exact: true }).waitFor();
  entry.device.settings_state = "discovering";
  await publish();
  await page.clock.runFor(10_000);
  assert.equal(await page.getByRole("button", { name: "Retry", exact: true }).count(), 0);
  entry.device.settings_state = "ready";
  await publish();
  assert.equal(await page.getByRole("button", { name: "Retry", exact: true }).count(), 0);
  await page.clock.runFor(10_000);
  await page.getByRole("button", { name: "Retry", exact: true }).waitFor();
  entry.device.settings_state = "discovering";
  await publish();
  await page.clock.runFor(90_000);
  await page.getByRole("button", { name: "Retry", exact: true }).waitFor();
  entry.device.settings_state = "ready";
  entry.settings = { ...cachedSettings, current: false, loadError: "Cached list unavailable", result: {
    kind: "apply", error: "Some saved values couldn't be applied.", counts: {
      device_id: entry.device.device_id, revision: 1, count: 6, applied: 5, failed: 1, read: 0, unchanged: 0, unsupported: 0, uncertain: 0,
    },
  } };
  await publish();
  await page.clock.runFor(10_000);
  await page.getByText("Some saved values couldn't be applied. (5 applied, 1 failed)", { exact: true }).waitFor();
  await page.getByText("Couldn't read the device's settings.", { exact: true }).waitFor();
  await page.getByRole("button", { name: "Retry", exact: true }).waitFor();
  entry.settings.result = { kind: "refresh", error: "Some settings couldn't be read.", counts: { ...entry.settings.result.counts, applied: 0, read: 5 } };
  await publish();
  await page.getByRole("button", { name: /Example Mouse/ }).first().click();
  await page.getByRole("button", { name: /Example Keys/ }).first().click();
  await page.clock.runFor(10_000);
  assert.equal(await page.getByRole("button", { name: "Retry", exact: true }).count(), 1);
  await page.getByRole("button", { name: "Retry", exact: true }).click();
  assert.equal((await actions()).at(-1).type, "settings.reload");
  entry.settings.current = true;
  entry.settings.loadError = null;
  await publish();
  await page.getByRole("button", { name: "Retry", exact: true }).waitFor();
  assert.equal(await page.getByRole("button", { name: "Retry", exact: true }).count(), 1);
  entry.settings.current = false;
  entry.settings.loadError = "Cached list unavailable";
  await publish();
  await page.clock.runFor(10_000);
  entry.settings.result = { kind: "refresh", error: null, counts: { ...entry.settings.result.counts, read: 6, applied: 0, failed: 0 } };
  await publish();
  await page.getByText("6 read", { exact: true }).waitFor();
  await page.getByText("Couldn't read the device's settings.", { exact: true }).waitFor();
  entry.settings.result = null;
  entry.device.settings_error = "settings_unavailable";
  await publish();
  await page.getByRole("button", { name: "Retry", exact: true }).waitFor();
  assert.equal(await page.locator(".toast").count(), 0);

  entry.info = null;
  entry.infoCurrent = false;
  entry.infoError = "device.info got no response";
  await publish();
  await page.getByRole("tab", { name: "Details" }).click();
  await page.getByText("Reading information…", { exact: true }).waitFor();
  assert.equal(await page.getByText("Couldn't read information", { exact: true }).count(), 0);
  await page.clock.runFor(10_000);
  await page.getByText("Couldn't read information", { exact: true }).waitFor();
  assert.equal(await page.getByText("device.info got no response", { exact: true }).count(), 0);
  await app.evaluate(() => { globalThis.uiFail = "device.info.refresh"; });
  await page.getByRole("button", { name: "Retry", exact: true }).click();
  await page.getByText("Couldn't save this value.", { exact: true }).waitFor();
  assert.equal(await page.locator(".toast").count(), 0);
  await page.getByRole("button", { name: "Retry", exact: true }).waitFor();
  await app.evaluate(() => { globalThis.uiFail = null; });
  await page.getByRole("button", { name: "Retry", exact: true }).click();
  entry.info = [];
  entry.infoCurrent = true;
  entry.infoError = null;
  await publish();
  await page.getByRole("button", { name: "Refresh", exact: true }).waitFor();
  assert.ok((await actions()).some((a) => a.type === "device.info.refresh" && a.key === entry.key));
  await app.evaluate(() => { globalThis.uiFail = "device.info.refresh"; });
  await page.getByRole("button", { name: "Refresh", exact: true }).click();
  await page.getByRole("button", { name: "Retry", exact: true }).waitFor();
  await page.getByRole("button", { name: "Forget Device…", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Cancel", exact: true }).click();
  await page.getByRole("button", { name: "Retry", exact: true }).waitFor();
  await app.evaluate(() => { globalThis.uiFail = null; });
  await page.getByRole("button", { name: "Retry", exact: true }).click();
  await page.getByRole("button", { name: "Refresh", exact: true }).waitFor();

  state.scan = { adapterId: entry.adapterId, running: false, candidates: [], error: null };
  await publish();
  await page.getByRole("button", { name: "Add Device", exact: true }).click();
  const pairing = page.getByRole("dialog", { name: "Add Device", exact: true });
  await pairing.getByText("No devices found", { exact: true }).waitFor();
  await pairing.getByRole("button", { name: "Refresh", exact: true }).click();
  assert.ok((await actions()).some((a) => a.type === "scan.start" && a.adapterId === entry.adapterId));
  state.scan.error = "The search failed.";
  await publish();
  await pairing.getByRole("button", { name: "Retry", exact: true }).waitFor();
  state.scan.candidates = [{ candidate_id: "nearby", name: "Nearby Keyboard", transport: "ble", kind: "keyboard", rssi: null }];
  await publish();
  await pairing.getByRole("button", { name: "Pair", exact: true }).waitFor();
  await pairing.getByRole("button", { name: "Retry", exact: true }).waitFor();
  state.scan.error = null;
  await publish();
  await pairing.getByRole("button", { name: "Refresh", exact: true }).waitFor();
  await app.evaluate(() => { globalThis.uiFail = "pair.start"; });
  await pairing.getByRole("button", { name: "Pair", exact: true }).click();
  await pairing.getByText("Couldn't save this value.", { exact: true }).waitFor();
  await pairing.getByRole("button", { name: "Refresh", exact: true }).waitFor();
  assert.equal(await pairing.getByRole("button", { name: "Retry", exact: true }).count(), 0);
  await app.evaluate(() => { globalThis.uiFail = "scan.start"; });
  await pairing.getByRole("button", { name: "Refresh", exact: true }).click();
  await pairing.getByRole("button", { name: "Retry", exact: true }).waitFor();
  await app.evaluate(() => { globalThis.uiFail = null; });
  await pairing.getByRole("button", { name: "Retry", exact: true }).click();
  await pairing.getByRole("button", { name: "Refresh", exact: true }).waitFor();
  state.pairing = {
    adapterId: entry.adapterId, candidateId: "nearby", name: "Nearby Keyboard", phase: "failed", prompt: null, deviceKey: null, message: "Pairing failed.",
  };
  await publish();
  await pairing.getByRole("button", { name: "Retry", exact: true }).click();
  assert.ok((await actions()).some((a) => a.type === "pair.dismiss"));
  state.pairing.phase = "cancelled";
  state.pairing.message = "Adding the device was cancelled.";
  await publish();
  await pairing.getByRole("button", { name: "Refresh", exact: true }).waitFor();
  assert.equal(await pairing.getByRole("button", { name: "Retry", exact: true }).count(), 0);
  state.pairing.phase = "connected";
  state.pairing.message = null;
  await publish();
  await pairing.getByRole("button", { name: "Add Another", exact: true }).waitFor();
  await pairing.getByRole("button", { name: "Done", exact: true }).click();
  state.pairing = null;
  state.scan = null;
  state.adapters = [];
  state.devices = [];
  await page.getByRole("button", { name: "Overview", exact: true }).click();
  await publish();
  await page.getByRole("button", { name: "Refresh", exact: true }).click();
  assert.ok((await actions()).some((a) => a.type === "adapters.refresh"));
  assert.deepEqual(errors, []);
  console.log("Device UI: settings, recovery, and Refresh/Retry labels passed");
} catch (error) {
  console.error(await page.locator("body").innerText());
  throw error;
} finally {
  await app.close();
  await rm(profile, { recursive: true, force: true });
}
