// Generates the protobuf messages from proto/cordial.proto with buf and
// protoc-gen-es, and the key catalog from proto/keys.toml. `--check` fails
// when the checked-in output differs from regeneration.
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "smol-toml";

const root = fileURLToPath(new URL("../", import.meta.url));
const proto = join(root, "../../../proto");
const check = process.argv.includes("--check");

function messages(out) {
  // buf only reads module paths inside the current directory, so the schema
  // directory is the input and this package's buf.yaml is passed explicitly.
  execFileSync("buf", ["generate", proto, "--config", join(root, "buf.yaml"), "--template", join(root, "buf.gen.yaml"), "--output", out], {
    cwd: root,
    stdio: "inherit",
  });
  return readFileSync(join(out, "src/gen/cordial_pb.ts"), "utf8");
}

const constant = (key) => key.replace("{n}", "n").replace(/[.-]/g, "_").toUpperCase();

function keys() {
  const catalog = parse(readFileSync(join(proto, "keys.toml"), "utf8"));
  const live = catalog.key.filter((k) => !k.retired);
  const lines = [
    "// @generated by scripts/generate.mjs from proto/keys.toml",
    "import type { KeyEntry } from \"../keys.ts\";",
    "",
    ...live.map((k) => `export const ${constant(k.key)} = ${JSON.stringify(k.key)};`),
    "",
    "/** Every key in the catalog that is still in use. */",
    "export const KEYS: readonly KeyEntry[] = [",
    ...live.map((k) => {
      const entry = {
        key: k.key,
        adapter: k.lists.includes("adapter"),
        device: k.lists.includes("device"),
        setting: k.lists.includes("setting"),
        type: k.type,
        unit: k.unit ?? null,
        values: k.values ?? [],
      };
      const fields = Object.entries(entry).map(([name, value]) => `${name}: ${JSON.stringify(value).replaceAll(",", ", ")}`);
      return `  { ${fields.join(", ")} },`;
    }),
    "];",
    "",
    "/** Keys a client shows together with one Save. */",
    `export const ROWS: readonly (readonly string[])[] = ${JSON.stringify((catalog.row ?? []).map((r) => r.keys))};`,
    "",
  ];
  return lines.join("\n");
}

const temporary = mkdtempSync(join(tmpdir(), "cordial-protocol-"));
try {
  const outputs = [
    ["src/gen/cordial_pb.ts", messages(temporary)],
    ["src/gen/keys.ts", keys()],
  ];
  let stale = false;
  for (const [path, text] of outputs) {
    const file = join(root, path);
    if (!check) writeFileSync(file, text);
    else if (readFileSync(file, "utf8") !== text) {
      console.error(`${path} is out of date; run npm run generate`);
      stale = true;
    }
  }
  if (stale) process.exitCode = 1;
} finally {
  rmSync(temporary, { recursive: true, force: true });
}
